Repository open-source-uc/ramos-uc, pull requests merged in 2021-07, with the labels that each got.

#13 Add devcontainer support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .env.example
  .gitattributes
  .vscode/launch.json
  README.md
  docs/SETUP.md
  poetry.lock
  requirements-dev.txt
  requirements.txt
Labels: enhancement

#23 Scrapping: Refactorización y agendamiento
  .env.example
  apps/bc_scraper/__init__.py
  apps/bc_scraper/actions/__init__.py
  apps/bc_scraper/actions/banner.py
  apps/bc_scraper/actions/collect.py
  apps/bc_scraper/actions/delete.py
  apps/bc_scraper/actions/errors.py
  apps/bc_scraper/actions/queries.py
  apps/bc_scraper/actions/schedule.py
  apps/bc_scraper/actions/search.py
  apps/bc_scraper/actions/update.py
  apps/bc_scraper/apps.py
  apps/bc_scraper/management/commands/scrape.py
  apps/bc_scraper/scraper/__init__.py
  apps/bc_scraper/scraper/banner.py
  apps/bc_scraper/scraper/programs.py
  apps/bc_scraper/scraper/requirements.py
  apps/bc_scraper/scraper/search.py
  apps/bc_scraper/tasks.py
  apps/bc_scraper/tests.py
  apps/bc_scraper/urls.py
  apps/bc_scraper/views.py
  docs/SCHEDULER.md
  docs/SCRAPER.md
  docs/SETUP.md
  front/templates/scraper/schedule.html
  poetry.lock
  pyproject.toml
  ramosuc/settings.py
  ramosuc/urls.py
  requirements-dev.txt
  requirements.txt
  scrape/.gitignore
  scrape/json_dump.py
  scrape/main.py
  scrape/old_banner.py
  scrape/scraper/__init__.py
  scrape/settings.json.example
Labels: feature

#25 feat(planner): add button for Buscacursos
  front/assets/package-lock.json
  front/assets/src/planner.js
  front/assets/src/save.js
  front/templates/courses/planner.html
Labels: feature

#38 fix(dev): add node and psql to devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .env.example
  .gitignore
  docs/BACKUPS.md
  ramosuc/settings.py
Labels: bug
